/**
 * WordWriterID: Multi-Pass Transformation Engine
 * * Executes the document lifecycle in two distinct phases. The `discover` 
 * method performs a preliminary scan of the raw text, using `EngineSyntax` 
 * to identify all blocks and populate the `registry` with their hierarchical 
 * numbers and IDs. The `transform` method then cleans the document by 
 * removing blocks marked with `vacate: true` and uses the 
 * `Universal Reference Resolver` to swap every `[..ID]` tag with 
 * hyperlinked labels generated by the specific block's `ref` function.
 */

import { EngineSyntax } from './syntax.js';

export class WordWriterIDParser {
    constructor(registry) {
        this.registry = registry;
    }

    /**
     * Phase 1: Discovery
     * Scans the document to build the registry before any rendering happens.
     */
    discover(text) {
        this.registry.reset();
        
        // 1. Process Sections line-by-line (necessary for hierarchical order)
        text.split('\n').forEach(line => {
            const m = EngineSyntax.map.section.regex.exec(line);
            if (m) {
                this.registry.registerSection(m.groups.id, m.groups.level, m.groups.title);
            }
            EngineSyntax.map.section.regex.lastIndex = 0;
        });

        // 2. Process all other blocks defined in EngineSyntax
        Object.entries(EngineSyntax.map).forEach(([type, config]) => {
            if (type === 'section') return; // Already handled
            
            config.regex.lastIndex = 0;
            let match;
            while ((match = config.regex.exec(text)) !== null) {
                // Pass all captured groups (id, title, content, lang, etc.) as metadata
                this.registry.register(match.groups.id, type, { ...match.groups });
            }
        });
    }

    /**
     * Phase 2: Transformation
     * Cleans the text and resolves references.
     */
    transform(text) {
        let output = text;

        // 1. Remove "Vacated" Blocks (Citations, Footnotes definitions)
        // These are items meant for the bibliography/footer, not the body text.
        Object.values(EngineSyntax.map).forEach(config => {
            if (config.vacate) {
                // We use a simplified version of the regex to swallow trailing whitespace
                const vacateRegex = new RegExp(config.regex.source + '\\s*', 'gs');
                output = output.replace(vacateRegex, '');
            }
        });

        // 2. Universal Reference Resolver
        // Uses the utility regex compiled from "[..ID]" in syntax.js
        output = output.replace(EngineSyntax.utils.reference, (match, id) => {
            const entry = this.registry.ids.get(id);
            
            if (!entry) {
                return `<span class="ww-error">[Unknown ID: ${id}]</span>`;
            }
            
            const config = EngineSyntax.map[entry.type];
            const num = entry.numbers || entry.number;
            const label = config.ref(num);
            
            // Generate anchor attributes for back-linking (citations/footnotes)
            let anchorAttr = '';
            if (entry.type === 'footnote') anchorAttr = `id="fnref-${id}" `;
            if (entry.type === 'citation') anchorAttr = `id="citeref-${id}" `;

            return `<a ${anchorAttr}href="#${entry.type}-${id}" class="ww-ref-link">${label}</a>`;
        });

        return output;
    }
}